# Spark

## Pandas API

- Không nên dùng vì spark đang cố gắng mô phỏng hành vi của pandas
- Hành vi của pandas đụng chạm rất nhiều đến RAM. Ví dụ: Pandas luôn lưu shape và count trong RAM (với spark và các hệ thống phân tán, việc count tốn thời gian)

In [1]:
from pyspark.sql import SparkSession
import pyspark.pandas as ps

ps.set_option("compute.default_index_type", "distributed")
spark = SparkSession.builder.getOrCreate()

/home/longnb32/FPT/ops/ml-ops/.venv/lib/python3.11/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/28 01:24:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
spark

Create dataframe

In [2]:
ps_df = ps.DataFrame({
    'col1': [1,2,3],
    'col2': [4,5,6]
})

ps_df.head()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/12 08:50:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/05/12 08:50:49 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

   col1  col2
0     1     4
1     2     5
2     3     6

In [3]:
type(ps_df)

pyspark.pandas.frame.DataFrame

In [4]:
ps_df.info()

<class 'pyspark.pandas.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int64
 1   col2    3 non-null      int64
dtypes: int64(2)

In [5]:
ps_df.describe()

       col1  col2
count   3.0   3.0
mean    2.0   5.0
std     1.0   1.0
min     1.0   4.0
25%     1.0   4.0
50%     2.0   5.0
75%     3.0   6.0
max     3.0   6.0

In [5]:
ps_df = ps.read_parquet('../../data/test/parquet/yellow_tripdata_2010-01.parquet')
ps_df.head()

/home/longnb32/FPT/ops/ml-ops/.venv/lib/python3.11/site-packages/pyspark/pandas/utils.py:1038: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_parquet`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

            vendor_id      pickup_datetime     dropoff_datetime  passenger_count  trip_distance  pickup_longitude  pickup_latitude rate_code store_and_fwd_flag  dropoff_longitude  dropoff_latitude payment_type  fare_amount  surcharge  mta_tax  tip_amount  tolls_amount  total_amount
25769803776       VTS  2010-01-26 07:41:00  2010-01-26 07:45:00                1           0.75        -73.956778        40.767750         1               None         -73.965957         40.765232          CAS          4.5        0.0      0.5        0.00           0.0          5.00
25769803777       DDS  2010-01-30 23:31:00  2010-01-30 23:46:12                1           5.90        -73.996118        40.763932         1               None         -73.981512         40.741193          CAS         15.3        0.5      0.5        0.00           0.0         16.30
25769803778       DDS  2010-01-18 20:22:20  2010-01-18 20:38:12                1           4.00        -73.979673        40.783790         1               None         -73.917852         40.878560          CAS         11.7        0.5      0.5        0.00           0.0         12.70
25769803779       VTS  2010-01-09 01:18:00  2010-01-09 01:35:00                2           4.70        -73.977922        40.763997         1               None         -73.923908         40.759725          CAS         13.3        0.5      0.5        0.00           0.0         14.30
25769803780       CMT  2010-01-18 19:10:14  2010-01-18 19:17:07                1           0.60        -73.990924        40.734682         1                  0         -73.995511         40.739088          Cre          5.3        0.0      0.5        0.87           0.0          6.67

In [7]:
len(ps_df)

14863778

In [6]:
import pandas as pd

pd.read_parquet('../../data/test/parquet/yellow_tripdata_2010-01.parquet').head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,surcharge,mta_tax,tip_amount,tolls_amount,total_amount
0,VTS,2010-01-26 07:41:00,2010-01-26 07:45:00,1,0.75,-73.956778,40.767750,1,None,-73.965957,40.765232,CAS,4.5,0.0,0.5,0.00,0.0,5.00
1,DDS,2010-01-30 23:31:00,2010-01-30 23:46:12,1,5.90,-73.996118,40.763932,1,None,-73.981512,40.741193,CAS,15.3,0.5,0.5,0.00,0.0,16.30
2,DDS,2010-01-18 20:22:20,2010-01-18 20:38:12,1,4.00,-73.979673,40.783790,1,None,-73.917852,40.878560,CAS,11.7,0.5,0.5,0.00,0.0,12.70
3,VTS,2010-01-09 01:18:00,2010-01-09 01:35:00,2,4.70,-73.977922,40.763997,1,None,-73.923908,40.759725,CAS,13.3,0.5,0.5,0.00,0.0,14.30
4,CMT,2010-01-18 19:10:14,2010-01-18 19:17:07,1,0.60,-73.990924,40.734682,1,0,-73.995511,40.739088,Cre,5.3,0.0,0.5,0.87,0.0,6.67

## Quay trở lại với `spark.sql`

### Thử đọc 1 file parquet

- Đọc 1 file parquet lớn vch (~500MB) và quan sát hành vi của spark

- Phải tạo một session (với các config nếu cần) trước khi thao tác các thứ
    - Session này sẽ bao gồm các config về số lượng CPU, RAM có thể dùng, và nhiều thứ khác

In [2]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder.getOrCreate()
)
spark

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/12 10:24:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

- Đọc một file parquet dưới dạng 1 dataframe
    - Cái này sẽ không load hết lên RAM, nó chỉ ở đó (lazy evaluation)
    - Giả sử có 1 lệnh như `.show()` thì nó mới làm việc

In [3]:
df = spark.read.parquet('../../data/test/parquet/yellow_tripdata_2010-01.parquet')
df.show(5)

+---------+-------------------+-------------------+---------------+------------------+------------------+---------------+---------+------------------+------------------+----------------+------------+-----------+---------+-------+----------+------------+------------+
|vendor_id|    pickup_datetime|   dropoff_datetime|passenger_count|     trip_distance|  pickup_longitude|pickup_latitude|rate_code|store_and_fwd_flag| dropoff_longitude|dropoff_latitude|payment_type|fare_amount|surcharge|mta_tax|tip_amount|tolls_amount|total_amount|
+---------+-------------------+-------------------+---------------+------------------+------------------+---------------+---------+------------------+------------------+----------------+------------+-----------+---------+-------+----------+------------+------------+
|      VTS|2010-01-26 07:41:00|2010-01-26 07:45:00|              1|              0.75|        -73.956778|       40.76775|        1|              NULL|        -73.965957|       40.765232|         CAS|        4.5|      0.0|    0.5|       0.0|         0.0|         5.0|
|      DDS|2010-01-30 23:31:00|2010-01-30 23:46:12|              1|               5.9|-73.99611799999998|      40.763932|        1|              NULL|-73.98151199999998|       40.741193|         CAS|       15.3|      0.5|    0.5|       0.0|         0.0|        16.3|
|      DDS|2010-01-18 20:22:20|2010-01-18 20:38:12|              1|               4.0|        -73.979673|       40.78379|        1|              NULL|-73.91785199999998|        40.87856|         CAS|       11.7|      0.5|    0.5|       0.0|         0.0|        12.7|
|      VTS|2010-01-09 01:18:00|2010-01-09 01:35:00|              2|               4.7|        -73.977922|      40.763997|        1|              NULL|-73.92390799999998|       40.759725|         CAS|       13.3|      0.5|    0.5|       0.0|         0.0|        14.3|
|      CMT|2010-01-18 19:10:14|2010-01-18 19:17:07|              1|0.5999999999999999|        -73.990924|      40.734682|        1|                 0|-73.99551099999998|       40.739088|         Cre|        5.3|      0.0|    0.5|      0.87|         0.0|        6.67|
+---------+-------------------+-------------------+---------------+------------------+------------------+---------------+---------+------------------+------------------+----------------+------------+-----------+---------+-------+----------+------------+------------+
only showing top 5 rows

- In ra kiểu dữ liệu của dataframe

In [3]:
type(df)

pyspark.sql.classic.dataframe.DataFrame

- Thử một Pandas-like function
    - `.head()` trả về 1 list các đối tượng `Row`

In [6]:
df.head()

Row(vendor_id='VTS', pickup_datetime='2010-01-26 07:41:00', dropoff_datetime='2010-01-26 07:45:00', passenger_count=1, trip_distance=0.75, pickup_longitude=-73.956778, pickup_latitude=40.76775, rate_code='1', store_and_fwd_flag=None, dropoff_longitude=-73.965957, dropoff_latitude=40.765232, payment_type='CAS', fare_amount=4.5, surcharge=0.0, mta_tax=0.5, tip_amount=0.0, tolls_amount=0.0, total_amount=5.0)

- Partition lại dataframe. Hoàn toàn có thể phân bố lại số partition
- Hãy bắt đầu check default trước, sau đó phân bố lại

In [ ]:
df.rdd.getNumPartitions()

8

In [ ]:
num_partitions = 4  # Replace with the desired number of partitions
df = df.repartition(
    num_partitions
)  # Default using hash-based partition, which can potentially be lead to skew problem!

- In ra schema, cái này giống như `.info()` của Pandas, ngoại trừ việc nó không thống kê số lượng null, vì df có thể sẽ rất lớn và phân tán
- Các kiểu dữ liệu của spark được liệt kê tại `pyspark.sql.types`

```python
from pyspark.sql.types import StringType, FloatType, DoubleType, TimestampType, IntegerType
```

In [7]:
df.printSchema()

root
 |-- vendor_id: string (nullable = true)
 |-- pickup_datetime: string (nullable = true)
 |-- dropoff_datetime: string (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- pickup_longitude: double (nullable = true)
 |-- pickup_latitude: double (nullable = true)
 |-- rate_code: string (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- dropoff_longitude: double (nullable = true)
 |-- dropoff_latitude: double (nullable = true)
 |-- payment_type: string (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- surcharge: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- total_amount: double (nullable = true)

### Getting familiar with DataFrame via playing around with CSV

In [1]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder.appName('Spark for CSV').getOrCreate()
)
spark

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/12 13:58:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/05/12 13:58:43 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

- Read the csv file

In [ ]:
df_spark = spark.read.csv('../../data/test/csv/04.customer.csv', header=True, inferSchema=True)
df_spark.count()

122

- Check column names and their datatype

In [ ]:
df_spark.dtypes

[('customerNumber', 'int'),
 ('customerName', 'string'),
 ('contactLastName', 'string'),
 ('contactFirstName', 'string'),
 ('phone', 'string'),
 ('addressLine1', 'string'),
 ('addressLine2', 'string'),
 ('city', 'string'),
 ('state', 'string'),
 ('postalCode', 'string'),
 ('country', 'string'),
 ('salesRepEmployeeNumber', 'double'),
 ('creditLimit', 'double')]

- Thử tạo 1 `tmp_df` có các cột chứa các kiểu dữ liệu nêu trên

In [ ]:
from pyspark.sql import DataFrame
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DoubleType, TimestampType, IntegerType
from datetime import datetime, timedelta
import random

# schema = StructType([
#     StructField("str_col", StringType(), True),
#     StructField("float_col", FloatType(), True),
#     StructField("double_col", DoubleType(), True),
#     StructField("ts_col", TimestampType(), True),
#     StructField("int_col", IntegerType(), True),
# ])

schema = ["str_col", "float_col", "double_col", "ts_col", "int_col"]

base_time = datetime(2024, 1, 1)
data = [
    (
        f"name_{i}",
        round(random.uniform(0, 100), 2),
        random.uniform(0, 1000),
        base_time + timedelta(hours=i),
        random.randint(0, 1000),
    )
    for i in range(100)
]

# hàm này nhận vào list các rows (value only), cần có schema
# hoặc này nhận vào list các rows (dict[col_name, value]), không cần schema
tmp_df: DataFrame = spark.createDataFrame(data, schema=schema)
tmp_df.show(5)
tmp_df.printSchema()

+-------+---------+------------------+-------------------+-------+
|str_col|float_col|        double_col|             ts_col|int_col|
+-------+---------+------------------+-------------------+-------+
| name_0|    21.93| 704.0928756410188|2024-01-01 00:00:00|    401|
| name_1|    84.99| 942.2895674153132|2024-01-01 01:00:00|    923|
| name_2|    79.82| 571.5448763094547|2024-01-01 02:00:00|    833|
| name_3|    47.21|459.06382618035025|2024-01-01 03:00:00|    672|
| name_4|     97.3| 386.2496155163193|2024-01-01 04:00:00|    556|
+-------+---------+------------------+-------------------+-------+
only showing top 5 rows
root
 |-- str_col: string (nullable = true)
 |-- float_col: double (nullable = true)
 |-- double_col: double (nullable = true)
 |-- ts_col: timestamp (nullable = true)
 |-- int_col: long (nullable = true)

- Explore stuff

In [ ]:
df_spark.describe().show()

26/05/12 13:59:27 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+
|summary|    customerNumber|     customerName|contactLastName|contactFirstName|               phone|        addressLine1| addressLine2|  city|   state|        postalCode|  country|salesRepEmployeeNumber|      creditLimit|
+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+
|  count|               122|              122|            122|             122|                 122|                 122|           22|   122|      49|               115|      122|                   100|              122|
|   mean| 296.4016393442623|             NULL|           NULL|            NULL|      4.3613890055E9|                NULL|         NULL|  NULL|    NULL| 48070.73684210526|     NULL|               1395.94|67659.01639344262|
| stddev|117.07754439792896|             NULL|           NULL|            NULL|2.1363019502582848E9|                NULL|         NULL|  NULL|    NULL|36838.359087791556|     NULL|      165.671929676781|45043.37075099175|
|    min|               103|    ANG Resellers|        Accorti|          Adrian|   +49 89 61 08 9555|1 rue Alsace-Lorr...|1 Garden Road|Aachen|      BC|          530-0003|Australia|                1165.0|              0.0|
|    max|               496|giftsbymail.co.uk|      de Castro|        Zbyszek |          981-443655|        Åkergatan 24|    Suite 750| Århus|Victoria|           WX3 6FW|      USA|                1702.0|         227600.0|
+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+

- Pick 1 or a list columns, which also returns a dataframe
    - Can be accessed by `.select()` or by operator (`df['column name']`) just like pandas does

In [ ]:
df_spark.select(['customerNumber', 'customerName']).show(2)

+--------------+------------------+
|customerNumber|      customerName|
+--------------+------------------+
|           103| Atelier graphique|
|           112|Signal Gift Stores|
+--------------+------------------+
only showing top 2 rows

In [ ]:
df_spark[['customerNumber', 'customerName']].show(2)

+--------------+------------------+
|customerNumber|      customerName|
+--------------+------------------+
|           103| Atelier graphique|
|           112|Signal Gift Stores|
+--------------+------------------+
only showing top 2 rows

- Apply some filters

In [57]:
df_spark.\
    select(['customerNumber', 'customerName']).\
    filter((df_spark['country'] == 'France') & (df_spark['customerName'] == 'Mini Caravy')).\
    show()

+--------------+------------+
|customerNumber|customerName|
+--------------+------------+
|           209| Mini Caravy|
+--------------+------------+

In [58]:
df_spark[['customerNumber', 'customerName']].\
    filter((df_spark['country'] == 'France') & (df_spark['customerName'] == 'Mini Caravy')).\
    show()

+--------------+------------+
|customerNumber|customerName|
+--------------+------------+
|           209| Mini Caravy|
+--------------+------------+

- The operator `df['column name']` itself can not be shown. So whenever we need to see the content of a column, we use `.select()`, which returns a dataframe supporting `.show()`

In [ ]:
df_spark.select(['customerNumber']).show(2)

+--------------+
|customerNumber|
+--------------+
|           103|
|           112|
+--------------+
only showing top 2 rows

- Add column

In [ ]:
df_spark.withColumn('double_creditLimit', df_spark['creditLimit']*2).show(2)

+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+------------------+
|customerNumber|      customerName|contactLastName|contactFirstName|     phone|   addressLine1|addressLine2|     city|state|postalCode|country|salesRepEmployeeNumber|creditLimit|double_creditLimit|
+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+------------------+
|           103| Atelier graphique|        Schmitt|         Carine |40.32.2555| 54, rue Royale|        NULL|   Nantes| NULL|     44000| France|                1370.0|    21000.0|           42000.0|
|           112|Signal Gift Stores|           King|            Jean|7025551838|8489 Strong St.|        NULL|Las Vegas|   NV|     83030|    USA|                1166.0|    71800.0|          143600.0|
+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+------------------+
only showing top 2 rows

- Rename

In [ ]:
mapping = {
    'customerNumber': 'customer number',
    'customerName': 'customer name'
}
df_spark.withColumnsRenamed(mapping).show(2)

+---------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|customer number|     customer name|contactLastName|contactFirstName|     phone|   addressLine1|addressLine2|     city|state|postalCode|country|salesRepEmployeeNumber|creditLimit|
+---------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|            103| Atelier graphique|        Schmitt|         Carine |40.32.2555| 54, rue Royale|        NULL|   Nantes| NULL|     44000| France|                1370.0|    21000.0|
|            112|Signal Gift Stores|           King|            Jean|7025551838|8489 Strong St.|        NULL|Las Vegas|   NV|     83030|    USA|                1166.0|    71800.0|
+---------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
only showing top 2 rows

- Drop columns

In [ ]:
df_spark.drop('customerNumber', 'customerName').show(2)

+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|contactLastName|contactFirstName|     phone|   addressLine1|addressLine2|     city|state|postalCode|country|salesRepEmployeeNumber|creditLimit|
+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|        Schmitt|         Carine |40.32.2555| 54, rue Royale|        NULL|   Nantes| NULL|     44000| France|                1370.0|    21000.0|
|           King|            Jean|7025551838|8489 Strong St.|        NULL|Las Vegas|   NV|     83030|    USA|                1166.0|    71800.0|
+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
only showing top 2 rows

In [ ]:
drop_cols = ['customerName', 'customerNumber']
df_spark.drop(*drop_cols).show(2)

+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|contactLastName|contactFirstName|     phone|   addressLine1|addressLine2|     city|state|postalCode|country|salesRepEmployeeNumber|creditLimit|
+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|        Schmitt|         Carine |40.32.2555| 54, rue Royale|        NULL|   Nantes| NULL|     44000| France|                1370.0|    21000.0|
|           King|            Jean|7025551838|8489 Strong St.|        NULL|Las Vegas|   NV|     83030|    USA|                1166.0|    71800.0|
+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
only showing top 2 rows

### Handle missing data

In [19]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Handle missing data').getOrCreate()
spark

In [20]:
df_spark = spark.read.csv('../../data/test/csv/04.customer.csv', header=True, inferSchema=True)
df_spark.show(2)

+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|customerNumber|      customerName|contactLastName|contactFirstName|     phone|   addressLine1|addressLine2|     city|state|postalCode|country|salesRepEmployeeNumber|creditLimit|
+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
|          NULL| Atelier graphique|        Schmitt|         Carine |40.32.2555| 54, rue Royale|        NULL|   Nantes| NULL|     44000| France|                1370.0|    21000.0|
|           112|Signal Gift Stores|           King|            Jean|7025551838|8489 Strong St.|        NULL|Las Vegas|   NV|     83030|    USA|                1166.0|    71800.0|
+--------------+------------------+---------------+----------------+----------+---------------+------------+---------+-----+----------+-------+----------------------+-----------+
only showing top 2 rows

In [3]:
df_spark.describe().show()

26/05/14 07:06:25 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+
|summary|    customerNumber|     customerName|contactLastName|contactFirstName|               phone|        addressLine1| addressLine2|  city|   state|        postalCode|  country|salesRepEmployeeNumber|      creditLimit|
+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+
|  count|               122|              122|            122|             122|                 122|                 122|           22|   122|      49|               115|      122|                   100|              122|
|   mean| 296.4016393442623|             NULL|           NULL|            NULL|      4.3613890055E9|                NULL|         NULL|  NULL|    NULL| 48070.73684210526|     NULL|               1395.94|67659.01639344262|
| stddev|117.07754439792896|             NULL|           NULL|            NULL|2.1363019502582848E9|                NULL|         NULL|  NULL|    NULL|36838.359087791556|     NULL|      165.671929676781|45043.37075099175|
|    min|               103|    ANG Resellers|        Accorti|          Adrian|   +49 89 61 08 9555|1 rue Alsace-Lorr...|1 Garden Road|Aachen|      BC|          530-0003|Australia|                1165.0|              0.0|
|    max|               496|giftsbymail.co.uk|      de Castro|        Zbyszek |          981-443655|        Åkergatan 24|    Suite 750| Århus|Victoria|           WX3 6FW|      USA|                1702.0|         227600.0|
+-------+------------------+-----------------+---------------+----------------+--------------------+--------------------+-------------+------+--------+------------------+---------+----------------------+-----------------+

In [4]:
df_spark.printSchema()

root
 |-- customerNumber: integer (nullable = true)
 |-- customerName: string (nullable = true)
 |-- contactLastName: string (nullable = true)
 |-- contactFirstName: string (nullable = true)
 |-- phone: string (nullable = true)
 |-- addressLine1: string (nullable = true)
 |-- addressLine2: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- postalCode: string (nullable = true)
 |-- country: string (nullable = true)
 |-- salesRepEmployeeNumber: double (nullable = true)
 |-- creditLimit: double (nullable = true)

- Khi `.describe()` và `.printSchema()`
    - `describe` sẽ chạy thống kê cho một cột theo kiểu dữ liệu phổ biến nhất. Nghĩa là nếu trong 1 cột toàn float có chứa 1 giá trị string thì phần thống kê sẽ bỏ giá trị đó ra (cho các tác vụ liên quan đến tính toán)
    - `printSchema` sẽ in ra kiểu dữ liệu theo common logic, nghĩa là chọn kiểu dữ liệu tổng quát. Ví dụ 1 cột toàn float có chứa 1 giá trị string thì kiểu dữ liệu của cột sẽ là string

- Detect `NULL` value. Trong `pyspark` thì `NULL` và `NaN` là khác nhau. `NaN` là 1 giá trị được thiết kế cho kiểu số, `NULL` là trạng thái chung cho cả kiểu số và non-số
- Khi kiểu số chứa giá trị `NaN`, nó không `NULL`

In [5]:
[{col: df_spark.filter(df_spark[f'{col}'].isNull()).count()} for col in df_spark.columns]

[{'customerNumber': 0},
 {'customerName': 0},
 {'contactLastName': 0},
 {'contactFirstName': 0},
 {'phone': 0},
 {'addressLine1': 0},
 {'addressLine2': 100},
 {'city': 0},
 {'state': 73},
 {'postalCode': 7},
 {'country': 0},
 {'salesRepEmployeeNumber': 22},
 {'creditLimit': 0}]

In [6]:
df_spark.count()

122

- Xoá dòng có dữ liệu trống trong df

In [9]:
df_spark.dropna(how='any').count()

# xoá kiểu này thì bay hết dữ liệu --> chỉ xoá những dòng có những cột thiếu nhất định (bằng cách lọc các dòng không bị xoá ra 1 df khác)

9

In [13]:
df_spark.filter(~df_spark['salesRepEmployeeNumber'].isNull() | ~df_spark['state'].isNull()).count()

102

In [16]:
# xoá những dòng có ít hơn `thresh` giá trị real
# hay có nhiều hơn len(df_spark.columns)-thresh giá trị null
# trong ví dụ này: Xoá các dòng có nhiều hơn 13-(13-2) = 2 giá trị null
df_spark.dropna(how='any', thresh=len(df_spark.columns)-2).count()

100

- Có thể xoá trên 1 subset các cột

In [17]:
# 122 - 7 = 115
df_spark.dropna(how='any', subset=['postalCode']).count()

115

- Fill nan

In [48]:
from pyspark.sql import functions as F

# collect() returns a list of rows
mean_value = df_spark.select(F.mean('customerNumber')).collect()[0][0]
df_spark.fillna(mean_value, subset=['customerNumber']).show()

+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
|customerNumber|        customerName|contactLastName|contactFirstName|            phone|        addressLine1|        addressLine2|         city|   state|postalCode|  country|salesRepEmployeeNumber|creditLimit|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
|           298|   Atelier graphique|        Schmitt|         Carine |       40.32.2555|      54, rue Royale|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|    21000.0|
|           112|  Signal Gift Stores|           King|            Jean|       7025551838|     8489 Strong St.|                NULL|    Las Vegas|      NV|     83030|      USA|                1166.0|    71800.0|
|           114|Australian Collec...|       Ferguson|           Peter|     03 9520 4555|   636 St Kilda Road|             Level 3|    Melbourne|Victoria|      3004|Australia|                1611.0|   117300.0|
|           119|   La Rochelle Gifts|        Labrune|         Janine |       40.67.8555|67, rue des Cinqu...|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|   118200.0|
|           121|  Baane Mini Imports|     Bergulfsen|          Jonas |       07-98 9555|Erling Skakkes ga...|                NULL|      Stavern|    NULL|      4110|   Norway|                1504.0|    81700.0|
|           124|Mini Gifts Distri...|         Nelson|           Susan|       4155551450|     5677 Strong St.|                NULL|   San Rafael|      CA|     97562|      USA|                1165.0|   210500.0|
|           125|  Havel & Zbyszek Co|Piestrzeniewicz|        Zbyszek |    (26) 642-7555|     ul. Filtrowa 68|                NULL|     Warszawa|    NULL|    01-012|   Poland|                  NULL|        0.0|
|           128|Blauer See Auto, Co.|         Keitel|          Roland|+49 69 66 90 2555|       Lyonerstr. 34|                NULL|    Frankfurt|    NULL|     60528|  Germany|                1504.0|    59700.0|
|           129|     Mini Wheels Co.|         Murphy|           Julie|       6505555787|5557 North Pendal...|                NULL|San Francisco|      CA|     94217|      USA|                1165.0|    64600.0|
|           131|   Land of Toys Inc.|            Lee|            Kwai|       2125557818|897 Long Airport ...|                NULL|          NYC|      NY|     10022|      USA|                1323.0|   114900.0|
|           141|Euro+ Shopping Ch...|         Freyre|          Diego |   (91) 555 94 44|  C/ Moralzarzal, 86|                NULL|       Madrid|    NULL|     28034|    Spain|                1370.0|   227600.0|
|           144|Volvo Model Repli...|       Berglund|      Christina |     0921-12 3555|     Berguvsvägen  8|                NULL|        Luleå|    NULL|  S-958 22|   Sweden|                1504.0|    53100.0|
|           145|Danish Wholesale ...|       Petersen|          Jytte |       31 12 3555|        Vinbæltet 34|                NULL|    Kobenhavn|    NULL|      1734|  Denmark|                1401.0|    83400.0|
|           146|Saveley & Henriot...|        Saveley|           Mary |       78.32.5555|  2, rue du Commerce|                NULL|         Lyon|    NULL|     69004|   France|                1337.0|   123900.0|
|           148|Dragon Souveniers...|      Natividad|            Eric|     +65 221 7555|          Bronz Sok.|Bronz Apt. 3/6 Te...|    Singapore|    NULL|    079903|Singapore|                1621.0|   103800.0|
|           151|  Muscle Machine Inc|          Young|            Jeff|       2125557413|   4092 Furth Circle|           Suite 400|          NYC|      NY|     10022|      USA|                1286.0|   138500.0|
|           157|Diecast Classics ...|          Leong|          Kelvin|       2155551555|    7586 Pompton St.|                NULL|    Allentown|      PA|     70267|      USA|                1216.0|   100600.0|
|           161|Technics Stores Inc.|      Hashimoto|            Juri|       6505556809|   9408 Furth Circle|                NULL|   Burlingame|      CA|     94217|      USA|                1165.0|    84600.0|
|           166|    Handji Gifts& Co|      Victorino|           Wendy|     +65 224 1555|106 Linden Road S...|           2nd Floor|    Singapore|    NULL|    069045|Singapore|                1612.0|    97900.0|
|           167|        Herkku Gifts|         Oeztan|          Veysel|    +47 2267 3215|     Brehmen St. 121|      PR 334 Sentrum|       Bergen|    NULL|    N 5804| Norway  |                1504.0|    96800.0|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
only showing top 20 rows

In [52]:
# fill nan with median
median_value = df_spark.select(F.median('customerNumber')).collect()[0][0]
df_spark.fillna(median_value, subset=['customerNumber']).show()

+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
|customerNumber|        customerName|contactLastName|contactFirstName|            phone|        addressLine1|        addressLine2|         city|   state|postalCode|  country|salesRepEmployeeNumber|creditLimit|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
|           299|   Atelier graphique|        Schmitt|         Carine |       40.32.2555|      54, rue Royale|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|    21000.0|
|           112|  Signal Gift Stores|           King|            Jean|       7025551838|     8489 Strong St.|                NULL|    Las Vegas|      NV|     83030|      USA|                1166.0|    71800.0|
|           114|Australian Collec...|       Ferguson|           Peter|     03 9520 4555|   636 St Kilda Road|             Level 3|    Melbourne|Victoria|      3004|Australia|                1611.0|   117300.0|
|           119|   La Rochelle Gifts|        Labrune|         Janine |       40.67.8555|67, rue des Cinqu...|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|   118200.0|
|           121|  Baane Mini Imports|     Bergulfsen|          Jonas |       07-98 9555|Erling Skakkes ga...|                NULL|      Stavern|    NULL|      4110|   Norway|                1504.0|    81700.0|
|           124|Mini Gifts Distri...|         Nelson|           Susan|       4155551450|     5677 Strong St.|                NULL|   San Rafael|      CA|     97562|      USA|                1165.0|   210500.0|
|           125|  Havel & Zbyszek Co|Piestrzeniewicz|        Zbyszek |    (26) 642-7555|     ul. Filtrowa 68|                NULL|     Warszawa|    NULL|    01-012|   Poland|                  NULL|        0.0|
|           128|Blauer See Auto, Co.|         Keitel|          Roland|+49 69 66 90 2555|       Lyonerstr. 34|                NULL|    Frankfurt|    NULL|     60528|  Germany|                1504.0|    59700.0|
|           129|     Mini Wheels Co.|         Murphy|           Julie|       6505555787|5557 North Pendal...|                NULL|San Francisco|      CA|     94217|      USA|                1165.0|    64600.0|
|           131|   Land of Toys Inc.|            Lee|            Kwai|       2125557818|897 Long Airport ...|                NULL|          NYC|      NY|     10022|      USA|                1323.0|   114900.0|
|           141|Euro+ Shopping Ch...|         Freyre|          Diego |   (91) 555 94 44|  C/ Moralzarzal, 86|                NULL|       Madrid|    NULL|     28034|    Spain|                1370.0|   227600.0|
|           144|Volvo Model Repli...|       Berglund|      Christina |     0921-12 3555|     Berguvsvägen  8|                NULL|        Luleå|    NULL|  S-958 22|   Sweden|                1504.0|    53100.0|
|           145|Danish Wholesale ...|       Petersen|          Jytte |       31 12 3555|        Vinbæltet 34|                NULL|    Kobenhavn|    NULL|      1734|  Denmark|                1401.0|    83400.0|
|           146|Saveley & Henriot...|        Saveley|           Mary |       78.32.5555|  2, rue du Commerce|                NULL|         Lyon|    NULL|     69004|   France|                1337.0|   123900.0|
|           148|Dragon Souveniers...|      Natividad|            Eric|     +65 221 7555|          Bronz Sok.|Bronz Apt. 3/6 Te...|    Singapore|    NULL|    079903|Singapore|                1621.0|   103800.0|
|           151|  Muscle Machine Inc|          Young|            Jeff|       2125557413|   4092 Furth Circle|           Suite 400|          NYC|      NY|     10022|      USA|                1286.0|   138500.0|
|           157|Diecast Classics ...|          Leong|          Kelvin|       2155551555|    7586 Pompton St.|                NULL|    Allentown|      PA|     70267|      USA|                1216.0|   100600.0|
|           161|Technics Stores Inc.|      Hashimoto|            Juri|       6505556809|   9408 Furth Circle|                NULL|   Burlingame|      CA|     94217|      USA|                1165.0|    84600.0|
|           166|    Handji Gifts& Co|      Victorino|           Wendy|     +65 224 1555|106 Linden Road S...|           2nd Floor|    Singapore|    NULL|    069045|Singapore|                1612.0|    97900.0|
|           167|        Herkku Gifts|         Oeztan|          Veysel|    +47 2267 3215|     Brehmen St. 121|      PR 334 Sentrum|       Bergen|    NULL|    N 5804| Norway  |                1504.0|    96800.0|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+
only showing top 20 rows

### Apply a function to a column

In [54]:
from pyspark.sql.types import StringType

def create_fullname(first_name:str, last_name:str):
    return first_name + ' ' + last_name

create_fullname_udf = F.udf(create_fullname, StringType())

df_spark.withColumn('Full name', create_fullname_udf(df_spark['contactLastName'], df_spark['contactFirstName'])).show()

/home/longnb32/FPT/ops/ml-ops/.venv/lib/python3.11/site-packages/pyspark/sql/udf.py:134: UserWarning: Cannot infer the eval type from type hints.
  warnings.warn("Cannot infer the eval type from type hints. ", UserWarning)

+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+--------------------+
|customerNumber|        customerName|contactLastName|contactFirstName|            phone|        addressLine1|        addressLine2|         city|   state|postalCode|  country|salesRepEmployeeNumber|creditLimit|           Full name|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+--------------------+
|          NULL|   Atelier graphique|        Schmitt|         Carine |       40.32.2555|      54, rue Royale|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|    21000.0|     Schmitt Carine |
|           112|  Signal Gift Stores|           King|            Jean|       7025551838|     8489 Strong St.|                NULL|    Las Vegas|      NV|     83030|      USA|                1166.0|    71800.0|           King Jean|
|           114|Australian Collec...|       Ferguson|           Peter|     03 9520 4555|   636 St Kilda Road|             Level 3|    Melbourne|Victoria|      3004|Australia|                1611.0|   117300.0|      Ferguson Peter|
|           119|   La Rochelle Gifts|        Labrune|         Janine |       40.67.8555|67, rue des Cinqu...|                NULL|       Nantes|    NULL|     44000|   France|                1370.0|   118200.0|     Labrune Janine |
|           121|  Baane Mini Imports|     Bergulfsen|          Jonas |       07-98 9555|Erling Skakkes ga...|                NULL|      Stavern|    NULL|      4110|   Norway|                1504.0|    81700.0|   Bergulfsen Jonas |
|           124|Mini Gifts Distri...|         Nelson|           Susan|       4155551450|     5677 Strong St.|                NULL|   San Rafael|      CA|     97562|      USA|                1165.0|   210500.0|        Nelson Susan|
|           125|  Havel & Zbyszek Co|Piestrzeniewicz|        Zbyszek |    (26) 642-7555|     ul. Filtrowa 68|                NULL|     Warszawa|    NULL|    01-012|   Poland|                  NULL|        0.0|Piestrzeniewicz Z...|
|           128|Blauer See Auto, Co.|         Keitel|          Roland|+49 69 66 90 2555|       Lyonerstr. 34|                NULL|    Frankfurt|    NULL|     60528|  Germany|                1504.0|    59700.0|       Keitel Roland|
|           129|     Mini Wheels Co.|         Murphy|           Julie|       6505555787|5557 North Pendal...|                NULL|San Francisco|      CA|     94217|      USA|                1165.0|    64600.0|        Murphy Julie|
|           131|   Land of Toys Inc.|            Lee|            Kwai|       2125557818|897 Long Airport ...|                NULL|          NYC|      NY|     10022|      USA|                1323.0|   114900.0|            Lee Kwai|
|           141|Euro+ Shopping Ch...|         Freyre|          Diego |   (91) 555 94 44|  C/ Moralzarzal, 86|                NULL|       Madrid|    NULL|     28034|    Spain|                1370.0|   227600.0|       Freyre Diego |
|           144|Volvo Model Repli...|       Berglund|      Christina |     0921-12 3555|     Berguvsvägen  8|                NULL|        Luleå|    NULL|  S-958 22|   Sweden|                1504.0|    53100.0| Berglund Christina |
|           145|Danish Wholesale ...|       Petersen|          Jytte |       31 12 3555|        Vinbæltet 34|                NULL|    Kobenhavn|    NULL|      1734|  Denmark|                1401.0|    83400.0|     Petersen Jytte |
|           146|Saveley & Henriot...|        Saveley|           Mary |       78.32.5555|  2, rue du Commerce|                NULL|         Lyon|    NULL|     69004|   France|                1337.0|   123900.0|       Saveley Mary |
|           148|Dragon Souveniers...|      Natividad|            Eric|     +65 221 7555|          Bronz Sok.|Bronz Apt. 3/6 Te...|    Singapore|    NULL|    079903|Singapore|                1621.0|   103800.0|      Natividad Eric|
|           151|  Muscle Machine Inc|          Young|            Jeff|       2125557413|   4092 Furth Circle|           Suite 400|          NYC|      NY|     10022|      USA|                1286.0|   138500.0|          Young Jeff|
|           157|Diecast Classics ...|          Leong|          Kelvin|       2155551555|    7586 Pompton St.|                NULL|    Allentown|      PA|     70267|      USA|                1216.0|   100600.0|        Leong Kelvin|
|           161|Technics Stores Inc.|      Hashimoto|            Juri|       6505556809|   9408 Furth Circle|                NULL|   Burlingame|      CA|     94217|      USA|                1165.0|    84600.0|      Hashimoto Juri|
|           166|    Handji Gifts& Co|      Victorino|           Wendy|     +65 224 1555|106 Linden Road S...|           2nd Floor|    Singapore|    NULL|    069045|Singapore|                1612.0|    97900.0|     Victorino Wendy|
|           167|        Herkku Gifts|         Oeztan|          Veysel|    +47 2267 3215|     Brehmen St. 121|      PR 334 Sentrum|       Bergen|    NULL|    N 5804| Norway  |                1504.0|    96800.0|       Oeztan Veysel|
+--------------+--------------------+---------------+----------------+-----------------+--------------------+--------------------+-------------+--------+----------+---------+----------------------+-----------+--------------------+
only showing top 20 rows

### Group by & Aggregate

In [1]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName('agg').getOrCreate()
spark

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/14 09:28:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
df_spark = spark.read.csv('../../data/test/csv/04.customer.csv', header=True, inferSchema=True)
df_spark.show(5)

+--------------+--------------------+---------------+----------------+------------+--------------------+------------+---------+--------+----------+---------+----------------------+-----------+
|customerNumber|        customerName|contactLastName|contactFirstName|       phone|        addressLine1|addressLine2|     city|   state|postalCode|  country|salesRepEmployeeNumber|creditLimit|
+--------------+--------------------+---------------+----------------+------------+--------------------+------------+---------+--------+----------+---------+----------------------+-----------+
|           103|   Atelier graphique|        Schmitt|         Carine |  40.32.2555|      54, rue Royale|        NULL|   Nantes|    NULL|     44000|   France|                1370.0|    21000.0|
|           112|  Signal Gift Stores|           King|            Jean|  7025551838|     8489 Strong St.|        NULL|Las Vegas|      NV|     83030|      USA|                1166.0|    71800.0|
|           114|Australian Collec...|       Ferguson|           Peter|03 9520 4555|   636 St Kilda Road|     Level 3|Melbourne|Victoria|      3004|Australia|                1611.0|   117300.0|
|           119|   La Rochelle Gifts|        Labrune|         Janine |  40.67.8555|67, rue des Cinqu...|        NULL|   Nantes|    NULL|     44000|   France|                1370.0|   118200.0|
|           121|  Baane Mini Imports|     Bergulfsen|          Jonas |  07-98 9555|Erling Skakkes ga...|        NULL|  Stavern|    NULL|      4110|   Norway|                1504.0|    81700.0|
+--------------+--------------------+---------------+----------------+------------+--------------------+------------+---------+--------+----------+---------+----------------------+-----------+
only showing top 5 rows

In [12]:
# count the number of order in every country/state/city
df_orderByCountry = df_spark.groupBy('country').count()
df_orderByCountry.select(F.sum(df_orderByCountry['count'])).show()

+----------+
|sum(count)|
+----------+
|       122|
+----------+

In [24]:
df_spark.groupBy('country').agg(F.max(df_spark['creditLimit'])).show()

+-----------+----------------+
|    country|max(creditLimit)|
+-----------+----------------+
|     Russia|             0.0|
|     Sweden|        116400.0|
|Philippines|         81500.0|
|  Singapore|        103800.0|
|    Germany|        120400.0|
|     France|        123900.0|
|    Belgium|         79900.0|
|    Finland|         98800.0|
|      Italy|        121400.0|
|     Norway|         81700.0|
|      Spain|        227600.0|
|    Denmark|        120800.0|
|    Ireland|         69400.0|
|  Hong Kong|         58600.0|
|     Israel|             0.0|
|        USA|        210500.0|
|   Norway  |         96800.0|
|         UK|        136800.0|
|Switzerland|        141300.0|
|     Canada|         90300.0|
+-----------+----------------+
only showing top 20 rows

In [28]:
%%timeit
df_spark.agg({'customerNumber': 'sum'}).show()

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

78 ms ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [29]:
%%timeit
df_spark.select(F.sum('customerNumber')).show()

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

+-------------------+
|sum(customerNumber)|
+-------------------+
|              36161|
+-------------------+

61.8 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

- Có vẻ việc dùng hàm sẽ ổn định hơn và nhanh hơn 1 chút so với việc truyền vào key, value cho `agg()` tự parse

In [62]:
# người có tín dụng cao nhất tại mỗi thành phố của Mỹ
maxCredByCity_df = df_spark.filter(df_spark.country=='USA').groupBy('city').agg(F.max('creditLimit')).alias('max_df')
maxCredByCity_df.join(
    df_spark.alias('orig_df'),
    (F.col('max_df.city') == F.col('orig_df.city')) & (maxCredByCity_df['max(creditLimit)'] == df_spark['creditLimit']),
    'inner'
)['max_df.city', 'customerName', 'max(creditLimit)'].show()

+-------------+--------------------+----------------+
|         city|        customerName|max(creditLimit)|
+-------------+--------------------+----------------+
|    Las Vegas|  Signal Gift Stores|         71800.0|
|   San Rafael|Mini Gifts Distri...|        210500.0|
|          NYC|  Muscle Machine Inc|        138500.0|
|    Allentown|Diecast Classics ...|        100600.0|
|   Burlingame|Technics Stores Inc.|         84600.0|
|  Bridgewater|     Gift Depot Inc.|         84300.0|
|     Pasadena|   Toys4GrownUps.com|         90700.0|
|    San Diego|Collectable Mini ...|        105000.0|
|    Cambridge|Marta s Replicas Co.|        123700.0|
| White Plains|       Mini Classics|        102700.0|
|  New Bedford| Mini Creations Ltd.|         94500.0|
|San Francisco|Corporate Gift Id...|        105000.0|
|       Newark|Tekni Collectable...|         43000.0|
| Philadelphia|Classic Gift Idea...|         81100.0|
|  Los Angeles|Men  R  US Retail...|         57700.0|
|       Nashua|Online Diecast Cr...|        114200.0|
|   Brickhaven|Collectables For ...|         70700.0|
|     Glendale|    Gift Ideas Corp.|         49700.0|
|     San Jose|The Sharp Gifts W...|         77600.0|
|    New Haven|    Super Scale Inc.|         95400.0|
+-------------+--------------------+----------------+
only showing top 20 rows

## Read DB

In [ ]:
# download postgres connector
!wget https://jdbc.postgresql.org/download/postgresql-42.7.11.jar

--2026-05-05 09:41:38--  https://jdbc.postgresql.org/download/postgresql-42.7.11.jar
Resolving jdbc.postgresql.org (jdbc.postgresql.org)... 72.32.157.228, 2001:4800:3e1:1::228
Connecting to jdbc.postgresql.org (jdbc.postgresql.org)|72.32.157.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1142677 (1.1M) [application/java-archive]
Saving to: ‘postgresql-42.7.11.jar’

postgresql-42.7.11. 100%[===================>]   1.09M  1.15MB/s    in 0.9s

2026-05-05 09:41:40 (1.15 MB/s) - ‘postgresql-42.7.11.jar’ saved [1142677/1142677]

In [ ]:
# access to S3
!wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.0/hadoop-aws-3.4.0.jar

In [1]:
from pyspark.sql import SparkSession
import os

spark = (
    SparkSession.builder.master("local[*]")
    .config(
        "spark.jars",
        os.path.abspath("../../spark/jar/postgresql-42.7.11.jar"),
    )
    .appName("Python Spark SQL basic example")
    .getOrCreate()
)

WARNING: Using incubator modules: jdk.incubator.vector
26/05/07 08:32:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [2]:
df = (
    spark.read.format("jdbc")
    .option("driver", "org.postgresql.Driver")
    .option("url", "jdbc:postgresql://localhost:5432/company")
    .option("dbtable", "public.nyc_taxi")
    .option("user", "company")
    .option("password", "company")
    .load()
)
df.show()

+---------+-------------------+-------------------+---------------+------------------+------------+------------------+------------------+---------------+------------------+----------------+--------------+--------------+------------+-----------+-----+-------+---------+---------------------+----------+------------+------------+--------------------+-----------+------------------+
|vendor_id|    pickup_datetime|   dropoff_datetime|passenger_count|     trip_distance|rate_code_id|store_and_fwd_flag|  pickup_longitude|pickup_latitude| dropoff_longitude|dropoff_latitude|pu_location_id|do_location_id|payment_type|fare_amount|extra|mta_tax|surcharge|improvement_surcharge|tip_amount|tolls_amount|total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|
+---------+-------------------+-------------------+---------------+------------------+------------+------------------+------------------+---------------+------------------+----------------+--------------+--------------+------------+-----------+-----+-------+---------+---------------------+----------+------------+------------+--------------------+-----------+------------------+
|      VTS|2009-01-04 02:52:00|2009-01-04 03:02:00|            1.0|              2.63|        NULL|              NULL|        -73.991957|      40.721567|        -73.993803|       40.695922|          NULL|          NULL|        CASH|        8.9| NULL|   NULL|      0.5|                 NULL|       0.0|         0.0|         9.4|                NULL|       NULL|              NULL|
|      CMT|2009-01-25 03:09:54|2009-01-25 03:29:36|            2.0|               7.2|        NULL|              NULL|-73.98807399999998|      40.732115|-73.90004999999998|       40.732515|          NULL|          NULL|        Cash|       19.8| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|        19.8|                NULL|       NULL|              NULL|
|      CMT|2009-01-21 18:37:31|2009-01-21 18:43:49|            1.0|               1.4|        NULL|              NULL|        -73.980947|      40.779788|-73.97147699999998|        40.79701|          NULL|          NULL|        Cash|        6.7| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|         6.7|                NULL|       NULL|              NULL|
|      VTS|2009-01-06 23:43:00|2009-01-06 23:42:00|            2.0|              1.87|        NULL|              NULL|        -73.983365|       40.75679|        -73.974018|       40.778737|          NULL|          NULL|      Credit|        6.5| NULL|   NULL|      0.5|                 NULL|       2.0|         0.0|         9.0|                NULL|       NULL|              NULL|
|      CMT|2009-01-09 04:44:37|2009-01-09 05:06:21|            1.0|              16.5|        NULL|              NULL|        -74.000388|      40.717516|-73.74158099999998|       40.719887|          NULL|          NULL|      Credit|       36.6| NULL|   NULL|      0.0|                 NULL|       4.0|         0.0|        40.6|                NULL|       NULL|              NULL|
|      CMT|2009-01-12 07:20:57|2009-01-12 07:31:51|            1.0|               2.8|        NULL|              NULL|        -73.952623|      40.783519|-73.98485499999998|       40.759654|          NULL|          NULL|        Cash|        9.3| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|         9.3|                NULL|       NULL|              NULL|
|      CMT|2009-01-17 23:34:41|2009-01-17 23:44:45|            1.0|               1.4|        NULL|              NULL|-73.99968699999998|      40.720659|-73.98654999999998|       40.732979|          NULL|          NULL|        Cash|        7.8| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|         7.8|                NULL|       NULL|              NULL|
|      VTS|2009-01-09 14:06:00|2009-01-09 14:14:00|            5.0|              2.81|        NULL|              NULL|        -73.979332|      40.764198|        -74.002412|       40.737913|          NULL|          NULL|      Credit|        9.7| NULL|   NULL|      0.0|                 NULL|       2.0|         0.0|        11.7|                NULL|       NULL|              NULL|
|      VTS|2009-01-24 04:28:00|2009-01-24 04:30:00|            2.0|              2.11|        NULL|              NULL|        -74.000882|       40.73183|        -73.981498|       40.758303|          NULL|          NULL|      Credit|        6.9| NULL|   NULL|      0.5|                 NULL|       0.0|         0.0|         7.4|                NULL|       NULL|              NULL|
|      VTS|2009-01-16 07:04:00|2009-01-16 07:17:00|            5.0|               4.1|        NULL|              NULL|        -73.968053|        40.8019|-73.98404999999998|        40.75504|          NULL|          NULL|      Credit|       11.7| NULL|   NULL|      0.0|                 NULL|       2.0|         0.0|        13.7|                NULL|       NULL|              NULL|
|      VTS|2009-01-21 19:00:00|2009-01-21 19:12:00|            1.0|              2.67|        NULL|              NULL|-74.00667699999998|      40.731847|        -73.978848|       40.752668|          NULL|          NULL|        CASH|        9.3| NULL|   NULL|      1.0|                 NULL|       0.0|         0.0|        10.3|                NULL|       NULL|              NULL|
|      CMT|2009-01-01 16:15:36|2009-01-01 16:19:34|            2.0|0.5999999999999999|        NULL|              NULL|-74.00233199999998|      40.738821|        -73.995647|       40.733494|          NULL|          NULL|        Cash|        4.5| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|         4.5|                NULL|       NULL|              NULL|
|      VTS|2009-01-02 21:02:00|2009-01-02 21:11:00|            5.0|              3.45|        NULL|              NULL|        -74.017655|       40.71186|        -73.997377|       40.747397|          NULL|          NULL|      Credit|       10.5| NULL|   NULL|      0.5|                 NULL|       3.0|         0.0|        14.0|                NULL|       NULL|              NULL|
|      CMT|2009-01-23 14:39:02|2009-01-23 15:35:15|            1.0|              17.3|        NULL|              NULL|               0.0|            0.0|               0.0|             0.0|          NULL|          NULL|      Credit|       45.0| NULL|   NULL|      0.0|                 NULL|       5.0|         0.0|        50.0|                NULL|       NULL|              NULL|
|      DDS|2009-02-03 08:25:00|2009-02-03 08:33:39|            1.0|               1.6|        NULL|              NULL|        -73.992768|      40.758325|         -73.99471|       40.739723|          NULL|          NULL|        CASH|        6.9| NULL|   NULL|      0.0|                 NULL|       0.0|         0.0|         6.9|                NULL|       NULL|              NULL|
|      DDS|2009-02-12 19:37:17|2009-02-12 19:52:14|            1.0|               3.0|        NULL|              NULL|        -73.956737|      40.778039|         -73.97557|       40.741804|          NULL|          NULL|        CASH|       10.5| NULL|   NULL|      1.0|                 NULL|       0.0|         0.0|        11.5|                NULL|       NULL|              NULL|
|      CMT|2009-02-07 07:12:32|2009-02-07 07:21:25|            1.0|               2.7|        NULL|              NULL|        -73.959646|      40.808942|        -73.951583|       40.781199|          NULL|          NULL|      Credit|        8.9| NULL|   NULL|      0.0|                 NULL|      1.33|         0.0|       10.23|                NULL|       NULL|              NULL|
|      VTS|2009-02-01 22:39:00|2009-02-01 22:44:00|            1.0|              1.18|        NULL|              NULL|        -74.006505|      40.743838|        -73.992748|       40.735623|          NULL|          NULL|        CASH|        5.7| NULL|   NULL|      0.5|                 NULL|       0.0|         0.0|         6.2|                NULL|       NULL|              NULL|
|      VTS|2009-02-27 01:40:00|2009-02-27 01:50:00|            5.0|              2.65|        NULL|              NULL|-73.98527799999998|      40.759593|        -73.968798|        40.79091|          NULL|          NULL|        CASH|        9.3| NULL|   NULL|      0.5|                 NULL|       0.0|         0.0|         9.8|                NULL|       NULL|              NULL|
|      CMT|2009-02-26 09:27:16|2009-02-26 09:50:21|            2.0|              10.9|        NULL|               0.0|        -74.007587|      40.704143|-73.90271199999998|        40.76678|          NULL|          NULL|      Credit|       25.7| NULL|   NULL|      0.0|                 NULL|      5.97|        4.15|       35.82|                NULL|       NULL|              NULL|
+---------+-------------------+-------------------+---------------+------------------+------------+------------------+------------------+---------------+------------------+----------------+--------------+--------------+------------+-----------+-----+-------+---------+---------------------+----------+------------+------------+--------------------+-----------+------------------+
only showing top 20 rows

In [3]:
df.describe().show()

26/05/07 08:32:40 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+
|summary|vendor_id|   passenger_count|     trip_distance|rate_code_id|  store_and_fwd_flag|  pickup_longitude|  pickup_latitude| dropoff_longitude| dropoff_latitude|pu_location_id|do_location_id|payment_type|       fare_amount|extra|            mta_tax|          surcharge|improvement_surcharge|        tip_amount|      tolls_amount|      total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|
+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+
|  count|      224|               224|               224|           0|                  72|               224|              224|               224|              224|             0|             0|         224|               224|    0|                 28|                224|                    0|               224|               224|               224|                   0|          0|                 0|
|   mean|     NULL|1.6919642857142858|2.7213392857142864|        NULL|0.013888888888888888|-71.99781276339289|39.66127633928571|-71.99188713392857|39.65844495535715|          NULL|          NULL|        NULL|10.123660714285718| NULL|0.48214285714285715|0.23214285714285715|                 NULL|0.5881696428571429|0.1149107142857143|11.121383928571431|                NULL|       NULL|              NULL|
| stddev|     NULL| 1.345554940302877|3.1046585842452528|        NULL|  0.1178511301977579|11.971368518647013|6.594732839545908|11.970285832209642|6.594122869885129|          NULL|          NULL|        NULL| 8.336941562157335| NULL| 0.0944911182523068|0.35389296492215916|                 NULL|1.2877629463802047|0.6949594246125335| 9.294019261884424|                NULL|       NULL|              NULL|
|    min|      CMT|               1.0|               0.0|        NULL|                 0.0|        -74.017655|              0.0|-74.01719799999998|              0.0|          NULL|          NULL|        CASH|               2.5| NULL|                0.0|                0.0|                 NULL|               0.0|               0.0|               2.5|                NULL|       NULL|              NULL|
|    max|      VTS|               6.0|             17.52|        NULL|                 1.0|               0.0|        41.366138|               0.0|        40.809885|          NULL|          NULL|   No Charge|              58.0| NULL|                0.5|                1.0|                 NULL|               9.0|              4.57|             58.15|                NULL|       NULL|              NULL|
+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+

In [16]:
df.summary().show()

26/05/06 16:28:42 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+
|summary|vendor_id|   passenger_count|     trip_distance|rate_code_id|  store_and_fwd_flag|  pickup_longitude|  pickup_latitude| dropoff_longitude| dropoff_latitude|pu_location_id|do_location_id|payment_type|       fare_amount|extra|            mta_tax|          surcharge|improvement_surcharge|        tip_amount|      tolls_amount|      total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|
+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+
|  count|      224|               224|               224|           0|                  72|               224|              224|               224|              224|             0|             0|         224|               224|    0|                 28|                224|                    0|               224|               224|               224|                   0|          0|                 0|
|   mean|     NULL|1.6919642857142858|2.7213392857142864|        NULL|0.013888888888888888|-71.99781276339289|39.66127633928571|-71.99188713392857|39.65844495535715|          NULL|          NULL|        NULL|10.123660714285718| NULL|0.48214285714285715|0.23214285714285715|                 NULL|0.5881696428571429|0.1149107142857143|11.121383928571431|                NULL|       NULL|              NULL|
| stddev|     NULL| 1.345554940302877|3.1046585842452528|        NULL|  0.1178511301977579|11.971368518647013|6.594732839545908|11.970285832209642|6.594122869885129|          NULL|          NULL|        NULL| 8.336941562157335| NULL| 0.0944911182523068|0.35389296492215916|                 NULL|1.2877629463802047|0.6949594246125335| 9.294019261884424|                NULL|       NULL|              NULL|
|    min|      CMT|               1.0|               0.0|        NULL|                 0.0|        -74.017655|              0.0|-74.01719799999998|              0.0|          NULL|          NULL|        CASH|               2.5| NULL|                0.0|                0.0|                 NULL|               0.0|               0.0|               2.5|                NULL|       NULL|              NULL|
|    25%|     NULL|               1.0|              1.08|        NULL|                 0.0|-73.99554999999998|        40.731847|        -73.990503|        40.734895|          NULL|          NULL|        NULL|               5.7| NULL|                0.5|                0.0|                 NULL|               0.0|               0.0|               6.4|                NULL|       NULL|              NULL|
|    50%|     NULL|               1.0|               1.9|        NULL|                 0.0|        -73.983365|        40.751015|        -73.981577|        40.750497|          NULL|          NULL|        NULL|               7.7| NULL|                0.5|                0.0|                 NULL|               0.0|               0.0| 8.279999999999998|                NULL|       NULL|              NULL|
|    75%|     NULL|               2.0|               2.7|        NULL|                 0.0|        -73.973346|        40.764618|        -73.969505|        40.764281|          NULL|          NULL|        NULL|              10.5| NULL|                0.5|                0.5|                 NULL|               0.9|               0.0|              11.7|                NULL|       NULL|              NULL|
|    max|      VTS|               6.0|             17.52|        NULL|                 1.0|               0.0|        41.366138|               0.0|        40.809885|          NULL|          NULL|   No Charge|              58.0| NULL|                0.5|                1.0|                 NULL|               9.0|              4.57|             58.15|                NULL|       NULL|              NULL|
+-------+---------+------------------+------------------+------------+--------------------+------------------+-----------------+------------------+-----------------+--------------+--------------+------------+------------------+-----+-------------------+-------------------+---------------------+------------------+------------------+------------------+--------------------+-----------+------------------+

In [6]:
df.createOrReplaceTempView('nyc_taxi')
rs = spark.sql('select count(*) from nyc_taxi')
rs.show()

+--------+
|count(1)|
+--------+
|     224|
+--------+